### ISSUE TITLE
Semantic segmentation code

### ISSUE THREAD

**Issue by Archer-pro666** [hancyran/RepSurf-Segmentation#1]
Hello, thank you for your excellent work!  When will the code for semantic segmentation be open sourced?

**Comment by hancyran** [comment]
Thank you for your interest in our work! We will release the segmentation codebase very recently.

**Comment by Archer-pro666** [comment]
ok, thank you

**Comment by ThorJonsson** [comment]
Hi are there any updates on this?

**Comment by YehLi** [comment]
When will the code be released?

**Comment by hancyran** [comment]
Hi folks, 
We have uploaded the segmentation code in the "segmentation" folder of our main git (https://github.com/hancyran/RepSurf) along with the pretrained models and the logs. Please feel free to check and use it! And this repo will be deprecated soon.

Thank you for your interest in our work!
